import java.text.SimpleDateFormat

package object data_parsing {

  val dateFormat = new SimpleDateFormat("yyyy-MM-dd")

  val borders_dictionary: Map[String, List[String]] = Map(
    "Andorra" -> List(
      "France",
      "Spain"
    ),
    "United Arab Emirates" -> List(
      "Oman",
      "Saudi Arabia"
    ),
    "Afgahnastan" -> List(
      "China",
      "Iran",
      "Pakistan",
      "Tajikastan",
      "Turkmenistan",
      "Uzbekistan"
    ),
    "Antigua and Barbuda" -> List(),
    "Anguilla" -> List(),
    "Albania" -> List(
      "Greece",
      "Montenegro",
      "Macedonia",
      "Serbia"
    ),
    "Armenia" -> List(
      "Azerbaijan",
      "Gerogia",
      "Iran",
      "Turkey"
    ),
    "Angola" -> List(
      "Congo",
      "Democratic Repbulic of Congo",
      "Nambia",
      "Zambia"
    ),
    "Antarctica" -> List(),
    "Argentina" -> List(
      "Bolivia",
      "Brazil",
      "Chile",
      "Paraguay",
      "Uruguay"
    ),
    "American Samoa" -> List(),
    "Austria" -> List(
      "Czechia",
      "Germany",
      "Hungary",
      "Italy",
      "Lietchenstien",
      "Slovakia",
      "Slovenia",
      "Switzerland"
    ),
    "Australia" -> List(),
    "Aruba" -> List(),
    "Aland Islands" -> List(),
    "Azerbaijan" -> List(
      "Armenia",
      "Georgia",
      "Iran",
      "Russia",
      "Turkey"
    ),
    "Bosnia and Herzegovina" -> List(
      "Croatia",
      "Montenegro",
      "Serbia"
    ),
    "Barbados" -> List(),
    "Bangladesh" -> List(
      "India",
      "Myanmar"
    ),
    "Belgium" -> List(
      "France",
      "Germany",
      "Luxembourg",
      "Netherlands"
    ),
    "Burkina Faso" -> List(
      "Benin",
      "Cote d'Ivoire",
      "Ghana",
      "Mali",
      "Niger",
      "Togo"
    ),
    "Bulgaria" -> List(
      "Greece",
      "Macedonia",
      "Romania",
      "Serbia",
      "Turkey"
    ),
    "Bahrain" -> List(),
    "Burundi" -> List(
      "Congo",
      "Rwanda",
      "Tanzania"
    ),
    "Benin" -> List(
      "Burkina Faso",
      "Niger",
      "Nigeria",
      "Togo"
    ),
    "Saint Bathelemy" -> List(),
    "Bermuda" -> List(),
    "Brunei Darussalam" -> List(
      "Malaysia"
    ),
    "Bolivia" -> List(
      "Argentina",
      "Brazil",
      "Chile",
      "Paraguay",
      "Peru"
    ),
    "Bonaire, Sint Eustatius and Saba" -> List(),
    "Brazil" -> List(
      "Argentina",
      "Bolivia",
      "Colombia",
      "French Guiana",
      "Guyana",
      "Paraguay",
      "Peru",
      "Suriname",
      "Uruguay",
      "Venezuela"
    ),
    "Bahamas" -> List(),
    "Bhutan" -> List(
      "China",
      "India"
    ),
    "Bouvet Island" -> List(),
    "Botswana" -> List(
      "Namibia",
      "South Africa",
      "Zambia",
      "Zimbabwe"
    ),
    "Belarus" -> List(
      "Latvia",
      "Lithuania",
      "Poland",
      "Russia",
      "Ukraine"
    ),
    "Belize" -> List(
      "Guatemala",
      "Mexico"
    ),
    "Canada" -> List(
      "United States"
    ),
    "Cocos (Keeling) Islands" -> List(),
    "Democratic Republic of Congo" -> List(
      "Angola",
      "Burundi",
      "Central African Republic",
      "Congo",
      "Rwanda",
      "South Sudan",
      "Tanzania",
      "Uganda",
      "Zambia"
    ),
    "Central African Republic" -> List(
      "Cameroon",
      "Chad",
      "Congo",
      "Congo",
      "South Sudan",
      "Sudan"
    ),
    "Congo" -> List(
      "Angola",
      "Cameroon",
      "Central African Republic",
      "Democratic Republic of Congo",
      "Gabon"
    ),
    "Switzerland" -> List(
      "Austria",
      "France",
      "Germany",
      "Italy",
      "Liechtenstein"
    ),
    "Cote d'Ivoire" -> List(
      "Burkina Faso",
      "Ghana",
      "Guinea",
      "Liberia",
      "Mali"
    ),
    "Cook Islands" -> List(),
    "Chile" -> List(
      "Argentina",
      "Bolivia",
      "Peru"
    ),
    "Cameroon" -> List(
      "Central African Republic",
      "Chad",
      "Congo",
      "Equatorial Guinea",
      "Gabon",
      "Nigeria"
    ),
    "China" -> List(
      "Afghanistan",
      "Bhutan",
      "Hong Kong",
      "India",
      "Kazakhstan",
      "North Korea",
      "Kyrgyzstan",
      "Laos",
      "Macao",
      "Mongolia",
      "Myanmar",
      "Nepal",
      "Pakistan",
      "Russia",
      "Tajikistan",
      "Vietnam"
    ),
    "Colombia" -> List(
      "Brazil",
      "Ecuador",
      "Panama",
      "Peru",
      "Venezuela"
    ),
    "Costa Rica" -> List(
      "Nicaragua",
      "Panama"
    ),
    "Cuba" -> List(),
    "Cabo Verde" -> List(),
    "Curcacao" -> List(),
    "Christmas Island" -> List(),
    "Czechia" -> List(
      "Austria",
      "Germany",
      "Poland",
      "Slovakia"
    ),
    "Germany" -> List(
      "Austria",
      "Belgium",
      "Czechia",
      "Denmark",
      "France",
      "Luxembourg",
      "Netherlands",
      "Poland",
      "Switzerland"
    ),
    "Djibouti" -> List(
      "Eritrea",
      "Ethiopia",
      "Somalia"
    ),
    "Denmark" -> List(
      "Germany"
    ),
    "Dominica" -> List(),
    "Dominican Republic" -> List(
      "Haiti"
    ),
    "Algeria" -> List(
      "Libya",
      "Mali",
      "Mauritania",
      "Morocco",
      "Niger",
      "Tunisia",
      "Western Sahara"
    ),
    "Ecuador" -> List(
      "Colombia",
      "Peru"
    ),
    "Estonia" -> List(
      "Latvia",
      "Russia"
    ),
    "Egypt" -> List(
      "Israel",
      "Libya",
      "Palestine",
      "Sudan"
    ),
    "Western Sahara" -> List(
      "Algeria",
      "Mauritania",
      "Morocco"
    ),
    "Eritrea" -> List(
      "Djibouti",
      "Ethiopia",
      "Sudan"
    ),
    "Spain" -> List(
      "Andorra",
      "France",
      "Gibraltar",
      "Morocco",
      "Portugal"
    ),
    "Ethiopia" -> List(
      "Djibouti",
      "Eritrea",
      "Kenya",
      "Somalia",
      "South Sudan",
      "Sudan"
    ),
    "Finland" -> List(
      "Norway",
      "Russia",
      "Sweden"
    ),
    "Fiji" -> List(),
    "Falkland Islands" -> List(),
    "Federated States of Micronesia" -> List(),
    "Faroe Island" -> List(),
    "France" -> List(
      "Andorra",
      "Belgium",
      "Germany",
      "Italy",
      "Luxembourg",
      "Monaco",
      "Spain",
      "Switzerland"
    ),
    "Gabon" -> List(
      "Cameroon",
      "Congo",
      "Equatorial Guinea"
    ),
    "United Kingdom" -> List(
      "France",
      "Ireland"
    ),
    "Grenada" -> List(),
    "Georgia" -> List(
      "Armenia",
      "Azerbaijan",
      "Russia",
      "Turkey"
    ),
    "French Guiana" -> List(
      "Brazil",
      "Suriname"
    ),
    "Guernsey" -> List(),
    "Ghana" -> List(
      "Burkina Faso",
      "Cote d’Ivoire",
      "Togo"
    ),
    "Gibraltar" -> List(
      "Spain"
    ),
    "Greenland" -> List(),
    "Gambia" -> List(
      "Senegal"
    ),
    "Guinea" -> List(
      "Cote d’Ivoire",
      "Guinea-Bissau",
      "Liberia",
      "Mali",
      "Senegal",
      "Sierra Leone"
    ),
    "Guadeloupe" -> List(),
    "Equatorial Guinea" -> List(
      "Cameroon",
      "Gabon"
    ),
    "Greece" -> List(
      "Albania",
      "Bulgaria",
      "Macedonia",
      "Turkey"
    ),
    "Guatemala" -> List(
      "Belize",
      "El Salvador",
      "Honduras",
      "Mexico"
    ),
    "Guam" -> List(),
    "Guinea-Bissau" -> List(
      "Guinea",
      "Senegal"
    ),
    "Guyana" -> List(
      "Brazil",
      "Suriname",
      "Venezuela"
    ),
    "Hong Kong" -> List(
      "China"
    ),
    "Honduras" -> List(
      "El Salvador",
      "Guatemala",
      "Nicaragua"
    ),
    "Croatia" -> List(
      "Bosnia and Herzegovina",
      "Hungary",
      "Montenegro",
      "Serbia",
      "Slovenia"
    ),
    "Haiti" -> List(
      "Dominican Republic"
    ),
    "Hungary" -> List(
      "Austria",
      "Croatia",
      "Romania",
      "Serbia",
      "Slovakia",
      "Slovenia",
      "Ukraine"
    ),
    "Indonesia" -> List(
      "Malaysia",
      "Papua New Guinea",
      "Timor-Leste"
    ),
    "Ireland" -> List(
      "United Kingdom"
    ),
    "Israel" -> List(
      "Egypt",
      "Jordan",
      "Lebanon",
      "Palestine",
      "Syria"
    ),
    "Isle of Man" -> List(),
    "India" -> List(
      "Bangladesh",
      "Bhutan",
      "China",
      "Myanmar",
      "Nepal",
      "Pakistan"
    ),
    "British Indian Ocean Territory" -> List(),
    "Iraq" -> List(
      "Iran",
      "Jordan",
      "Kuwait",
      "Saudi Arabia",
      "Syria",
      "Turkey"
    ),
    "Iran" -> List(
      "Afghanistan",
      "Armenia",
      "Azerbaijan",
      "Iraq",
      "Pakistan",
      "Turkey",
      "Turkmenistan"
    ),
    "Iceland" -> List(),
    "Italy" -> List(
      "Austria",
      "France",
      "San Marino",
      "Slovenia",
      "Switzerland",
      "Holy See"
    ),
    "Jersey" -> List(),
    "Jamaica" -> List(),
    "Jordan" -> List(
      "Iraq",
      "Israel",
      "Palestine",
      "Saudi Arabia",
      "Syria"
    ),
    "Japan" -> List(),
    "Kenya" -> List(
      "Ethiopia",
      "Somalia",
      "South Sudan",
      "Tanzania",
      "Uganda"
    ),
    "Kyrgyzstan" -> List(
      "China",
      "Kazakhstan",
      "Tajikistan",
      "Uzbekistan"
    ),
    "Cambodia" -> List(
      "Laos",
      "Thailand",
      "Vietnam"
    ),
    "Kiribati" -> List(),
    "Comorros" -> List(),
    "Saint Kitts and Nevis" -> List(),
    "North Korea" -> List(
      "China",
      "South Korea",
      "Russia"
    ),
    "South Korea" -> List(
      "North Korea"
    ),
    "Kuwait" -> List(
      "Iraq",
      "Saudi Arabia"
    ),
    "Cayman Island" -> List(),
    "Kazakhstan" -> List(
      "China",
      "Kyrgyzstan",
      "Russia",
      "Turkmenistan",
      "Uzbekistan"
    ),
    "Laos" -> List(
      "China",
      "Cambodia",
      "Myanmar",
      "Thailand",
      "Vietnam"
    ),
    "Lebanon" -> List(
      "Israel",
      "Syria"
    ),
    "Saint Lucia" -> List(),
    "Liechtenstien" -> List(
      "Austria",
      "Switzerland"
    ),
    "Sri Lanka" -> List(),
    "Liberia" -> List(
      "Cote d’Ivoire",
      "Guinea",
      "Sierra Leone"
    ),
    "Lesotho" -> List(
      "South Africa"
    ),
    "Lithuania" -> List(
      "Belarus",
      "Latvia",
      "Poland",
      "Russia"
    ),
    "Luxembourg" -> List(
      "Belarus",
      "Latvia",
      "Poland",
      "Russia"
    ),
    "Latvia" -> List(
      "Belarus",
      "Estonia",
      "Lithuania",
      "Russia"
    ),
    "Libya" -> List(
      "Algeria",
      "Chad",
      "Egypt",
      "Niger",
      "Sudan",
      "Tunisia"
    ),
    "Morocco" -> List(
      "Algeria",
      "Spain",
      "Western Sahara"
    ),
    "Monaco" -> List(
      "France"
    ),
    "Moldova" -> List(
      "Romania",
      "Ukraine"
    ),
    "Montenegro" -> List(
      "Albania",
      "Bosnia and Herzegovina",
      "Croatia",
      "Serbia"
    ),
    "Madagascar" -> List(),
    "Marshall Islands" -> List(),
    "Macedonia" -> List(
      "Albania",
      "Bulgaria",
      "Greece",
      "Serbia"
    ),
    "Mali" -> List(
      "Algeria",
      "Burkina Faso",
      "Cote d’Ivoire",
      "Guinea",
      "Mauritania",
      "Niger",
      "Senegal"
    ),
    "Myanmar" -> List(
      "Bangladesh",
      "China",
      "India",
      "Laos",
      "Thailand"
    ),
    "Mongolia" -> List(
      "China",
      "Russia"
    ),
    "Macao" -> List(
      "China"
    ),
    "Northern Mariana Islands" -> List(),
    "Martinique" -> List(),
    "Mauritania" -> List(
      "Algeria",
      "Mali",
      "Senegal",
      "Western Sahara"
    ),
    "Montserrat" -> List(),
    "Malta" -> List(),
    "Mauritius" -> List(),
    "Maldives" -> List(),
    "Malawi" -> List(
      "Mozambique",
      "Tanzania",
      "Zambia"
    ),
    "Mexico" -> List(
      "Belize",
      "Guatemala",
      "United States"
    ),
    "Malaysia" -> List(
      "Brunei Darussalam",
      "Indonesia",
      "Thailand"
    ),
    "Mozambique" -> List(
      "Malawi",
      "Eswatini",
      "South Africa",
      "Tanzania",
      "Zambia",
      "Zimbabwe"
    ),
    "Namibia" -> List(
      "Angola",
      "Botswana",
      "South Africa",
      "Zambia"
    ),
    "New Caldonia" -> List(),
    "Niger" -> List(
      "Algeria",
      "Benin",
      "Burkina Faso",
      "Chad",
      "Libya",
      "Mali",
      "Nigeria"
    ),
    "Norfolk Island" -> List(),
    "Nigeria" -> List(
      "Benin",
      "Cameroon",
      "Chad",
      "Niger"
    ),
    "Nicaragua" -> List(
      "Costa Rica",
      "Honduras"
    ),
    "Netherlands" -> List(
      "Belgium",
      "Germany"
    ),
    "Norway" -> List(
      "Finland",
      "Russia",
      "Sweden"
    ),
    "Nepal" -> List(
      "China",
      "India"
    ),
    "Nauru" -> List(),
    "Niue" -> List(),
    "New Zealand" -> List(),
    "Oman" -> List(
      "United Arab Emirates",
      "Saudi Arabia",
      "Yemen"
    ),
    "Panama" -> List(
      "Colombia",
      "Costa Rica"
    ),
    "Peru" -> List(
      "Bolivia",
      "Brazil",
      "Chile",
      "Colombia",
      "Ecuador"
    ),
    "French Polynesia" -> List(),
    "Papua New Guinea" -> List(
      "Indonesia"
    ),
    "Philippines" -> List(),
    "Pakistan" -> List(
      "Afghanistan",
      "China",
      "India",
      "Iran"
    ),
    "Poland" -> List(
      "Belarus",
      "Czechia",
      "Germany",
      "Lithuania",
      "Russia",
      "Slovakia",
      "Ukraine"
    ),
    "Saint Pierre and Miquelon" -> List(),
    "Pitcairn" -> List(),
    "Puerto Rico" -> List(),
    "Palestine" -> List(
      "Egypt",
      "Israel",
      "Jordan"
    ),
    "Portugal" -> List(
      "Spain"
    ),
    "Palau" -> List(),
    "Paraguay" -> List(
      "Argentina",
      "Bolivia",
      "Brazil"
    ),
    "Qatar" -> List(
      "Saudi Arabia"
    ),
    "Romania" -> List(
      "Bulgaria",
      "Hungary",
      "Moldova",
      "Serbia",
      "Ukraine"
    ),
    "Serbia" -> List(
      "Albania",
      "Bosnia and Herzegovina",
      "Bulgaria",
      "Croatia",
      "Hungary",
      "Montenegro",
      "Macedonia",
      "Romania"
    ),
    "Russia" -> List(
      "Azerbaijan",
      "Belarus",
      "China",
      "Estonia",
      "Finland",
      "Georgia",
      "Kazakhstan",
      "North Korea",
      "Latvia",
      "Lithuania",
      "Mongolia",
      "Norway",
      "Poland",
      "Ukraine"
    ),
    "Rwanda" -> List(
      "Burundi",
      "Congo",
      "Tanzania",
      "Uganda"
    ),
    "Saudi Arabia" -> List(
      "Iraq",
      "Jordan",
      "Kuwait",
      "Oman",
      "Qatar",
      "United Arab Emirates",
      "Yemen"
    ),
    "Solomon Islands" -> List(),
    "Seychelles" -> List(),
    "Sudan" -> List(
      "Central African Republic",
      "Chad",
      "Egypt",
      "Ethiopia",
      "Eritrea",
      "Libya",
      "South Sudan"
    ),
    "Sweden" -> List(
      "Finland",
      "Norway"
    ),
    "Singapore" -> List(),
    "Saint Helena" -> List(),
    "Slovenia" -> List(
      "Austria",
      "Croatia",
      "Hungary",
      "Italy"
    ),
    "Svalbard and Jan Mayen" -> List(),
    "Slovakia" -> List(
      "Austria",
      "Czechia",
      "Hungary",
      "Poland",
      "Ukraine"
    ),
    "Sierra Leone" -> List(
      "Guinea",
      "Liberia"
    ),
    "San Marino" -> List(
      "Italy"
    ),
    "Senegal" -> List(
      "Gambia",
      "Guinea",
      "Guinea-Bissau",
      "Mali",
      "Mauritania"
    ),
    "Somalia" -> List(
      "Djibouti",
      "Ethiopia",
      "Kenya"
    ),
    "Suriname" -> List(
      "Brazil",
      "French Guiana",
      "Guyana"
    ),
    "South Sudan" -> List(
      "Central African Republic",
      "Congo",
      "Ethiopia",
      "Kenya",
      "Sudan",
      "Uganda",
    ),
    "Sao Tome and Principe" -> List(),
    "El Salvador" -> List(
      "Guatemala",
      "Honduras"
    ),
    "Sint Maartin" -> List(),
    "Syria" -> List(
      "Iraq",
      "Israel",
      "Jordan",
      "Lebanon",
      "Turkey"
    ),
    "Eswatini" -> List(
      "Mozambique",
      "South Africa"
    ),
    "Turks and Caicos Islands" -> List(),
    "Chad" -> List(
      "Cameroon",
      "Central African Republic",
      "Libya",
      "Niger",
      "Nigeria",
      "Sudan"
    ),
    "Togo" -> List(
      "Benin",
      "Burkina Faso",
      "Ghana"
    ),
    "Thailand" -> List(
      "Cambodia",
      "Laos",
      "Malaysia",
      "Myanmar"
    ),
    "Tajikistan" -> List(
      "Afghanistan",
      "China",
      "Kyrgyzstan",
      "Uzbekistan"
    ),
    "Tokelau" -> List(),
    "Timor-Leste" -> List(),
    "Turkmenistan" -> List(
      "Indonesia",
      "Afghanistan",
      "Iran",
      "Kazakhstan",
      "Uzbekistan"
    ),
    "Tunisia" -> List(
      "Algeria",
      "Libya"
    ),
    "Tonga" -> List(),
    "Turkey" -> List(
      "Armenia",
      "Azerbaijan",
      "Bulgaria",
      "Georgia",
      "Greece",
      "Iran",
      "Iraq",
      "Syria"
    ),
    "Trinidad and Tobago" -> List(),
    "Tuvalu" -> List(),
    "Taiwan" -> List(),
    "Tanzania" -> List(
      "Burundi",
      "Congo",
      "Kenya",
      "Malawi",
      "Mozambique",
      "Rwanda",
      "Uganda",
      "Zambia"
    ),
    "Ukraine" -> List(
      "Belarus",
      "Hungary",
      "Moldova",
      "Poland",
      "Romania",
      "Russia",
      "Slovakia"
    ),
    "Uganda" -> List(
      "Congo",
      "Kenya",
      "Rwanda",
      "South Sudan",
      "Tanzania"
    ),
    "United States" -> List(
      "Canada",
      "Mexico"
    ),
    "Uruguay" -> List(
      "Argentina",
      "Brazil"
    ),
    "Uzbekistan" -> List(
      "Afghanistan",
      "Kazakhstan",
      "Kyrgyzstan",
      "Tajikistan",
      "Turkmenistan"
    ),
    "Holy See" -> List(
      "Italy"
    ),
    "Venezuela" -> List(
      "Brazil",
      "Colombia",
      "Guyana"
    ),
    "Virgin Islands" -> List(),
    "Vietnam" -> List(
      "Cambodia",
      "China",
      "Laos"
    ),
    "Vanuatu" -> List(),
    "Samoa" -> List(),
    "Yemen" -> List(
      "Oman",
      "Saudi Arabia"
    ),
    "South Africa" -> List(
      "Botswana",
      "Lesotho",
      "Mozambique",
      "Namibia",
      "Eswatini",
      "Zimbabwe"
    ),
    "Zambia" -> List(
      "Angola",
      "Botswana",
      "Congo",
      "Malawi",
      "Mozambique",
      "Namibia",
      "Tanzania",
      "Zimbabwe"
    ),
    "Zimbabwe" -> List(
      "Botswana",
      "Mozambique",
      "South Africa",
      "Zambia"
    )
  )

  val landlocked: List[String] = List(
    "Afghanistan",
    "Andorra",
    "Armenia",
    "Austria",
    "Azerbaijan",
    "Belarus",
    "Bhutan",
    "Bolivia",
    "Botswana",
    "Burkina Faso",
    "Burundi",
    "Central African Republic",
    "Chad",
    "Czech Republic",
    "Ethiopia",
    "Hungary",
    "Kazakhstan",
    "Kosovo",
    "Kyrgyzstan",
    "Laos",
    "Lesotho",
    "Liechtenstein",
    "Luxembourg",
    "Macedonia",
    "Malawi",
    "Mali",
    "Moldova",
    "Mongolia",
    "Nepal",
    "Niger",
    "Paraguay",
    "Rwanda",
    "San Marino",
    "Serbia",
    "Slovakia",
    "South Sudan",
    "Swaziland",
    "Switzerland",
    "Tajikistan",
    "Turkmenistan",
    "Uganda",
    "Uzbekistan",
    "Holy See",
    "Zambia",
    "Zimbabwe"
  )

  val doubly_landlocked: List[String] = List(
    "Liechtenstein",
    "Uzbekistan"
  )

  val country_codes_a2: Map[String, String] = Map(
    "AF" -> 	"Afghanistan",
    "AL" -> 	"Albania",
    "DZ" -> 	"Algeria",
    "AS" -> 	"American Samoa",
    "AD" -> 	"Andorra",
    "AO" -> 	"Angola",
    "AI" -> 	"Anguilla",
    "AQ" -> 	"Antarctica",
    "AG" -> 	"Antigua and Barbuda",
    "AR" -> 	"Argentina",
    "AM" -> 	"Armenia",
    "AW" -> 	"Aruba",
    "AU" -> 	"Australia",
    "AT" -> 	"Austria",
    "AZ" -> 	"Azerbaijan",
    "BS" -> 	"Bahamas",
    "BH" -> 	"Bahrain",
    "BD" -> 	"Bangladesh",
    "BB" -> 	"Barbados",
    "BY" -> 	"Belarus",
    "BE" -> 	"Belgium",
    "BZ" -> 	"Belize",
    "BJ" -> 	"Benin",
    "BM" -> 	"Bermuda",
    "BT" -> 	"Bhutan",
    "BO" -> 	"Bolivia",
    "BQ" -> 	"Bonaire, Sint Eustatius and Saba",
    "BA" -> 	"Bosnia and Herzegovina",
    "BW" -> 	"Botswana",
    "BV" -> 	"Bouvet Island",
    "BR" -> 	"Brazil",
    "IO" -> 	"British Indian Ocean Territory",
    "BN" -> 	"Brunei Darussalam",
    "BG" -> 	"Bulgaria",
    "BF" -> 	"Burkina Faso",
    "BI" -> 	"Burundi",
    "CV" -> 	"Cabo Verde",
    "KH" -> 	"Cambodia",
    "CM" -> 	"Cameroon",
    "CA" -> 	"Canada",
    "KY" -> 	"Cayman Islands",
    "CF" -> 	"Central African Republic",
    "TD" -> 	"Chad",
    "CL" -> 	"Chile",
    "CN" -> 	"China",
    "CX" -> 	"Christmas Island",
    "CC" -> 	"Cocos (Keeling) Islands",
    "CO" -> 	"Colombia",
    "KM" -> 	"Comoros",
    "CD" -> 	"Democratic Republic of the Congo",
    "CG" -> 	"Congo",
    "CK" -> 	"Cook Islands",
    "CR" -> 	"Costa Rica",
    "HR" -> 	"Croatia",
    "CU" -> 	"Cuba",
    "CW" -> 	"Curacao",
    "CY" -> 	"Cyprus",
    "CZ" -> 	"Czechia",
    "CI" -> 	"Cote d'Ivoire",
    "DK" -> 	"Denmark",
    "DJ" -> 	"Djibouti",
    "DM" -> 	"Dominica",
    "DO" -> 	"Dominican Republic",
    "EC" -> 	"Ecuador",
    "EG" -> 	"Egypt",
    "SV" -> 	"El Salvador",
    "GQ" -> 	"Equatorial Guinea",
    "ER" -> 	"Eritrea",
    "EE" -> 	"Estonia",
    "SZ" -> 	"Eswatini",
    "ET" -> 	"Ethiopia",
    "FK" -> 	"Falkland Islands",
    "FO" -> 	"Faroe Islands",
    "FJ" -> 	"Fiji",
    "FI" -> 	"Finland",
    "FR" -> 	"France",
    "GF" -> 	"French Guiana",
    "PF" -> 	"French Polynesia",
    "TF" -> 	"French Southern Territories",
    "GA" -> 	"Gabon",
    "GM" -> 	"Gambia",
    "GE" -> 	"Georgia",
    "DE" -> 	"Germany",
    "GH" -> 	"Ghana",
    "GI" -> 	"Gibraltar",
    "GR" -> 	"Greece",
    "GL" -> 	"Greenland",
    "GD" -> 	"Grenada",
    "GP" -> 	"Guadeloupe",
    "GU" -> 	"Guam",
    "GT" -> 	"Guatemala",
    "GG" -> 	"Guernsey",
    "GN" -> 	"Guinea",
    "GW" -> 	"Guinea-Bissau",
    "GY" -> 	"Guyana",
    "HT" -> 	"Haiti",
    "HM" -> 	"Heard Island and McDonald Islands",
    "VA" -> 	"Holy See",
    "HN" -> 	"Honduras",
    "HK" -> 	"Hong Kong",
    "HU" -> 	"Hungary",
    "IS" -> 	"Iceland",
    "IN" -> 	"India",
    "ID" -> 	"Indonesia",
    "IR" -> 	"Iran",
    "IQ" -> 	"Iraq",
    "IE" -> 	"Ireland",
    "IM" -> 	"Isle of Man",
    "IL" -> 	"Israel",
    "IT" -> 	"Italy",
    "JM" -> 	"Jamaica",
    "JP" -> 	"Japan",
    "JE" -> 	"Jersey",
    "JO" -> 	"Jordan",
    "KZ" -> 	"Kazakhstan",
    "KE" -> 	"Kenya",
    "KI" -> 	"Kiribati",
    "KP" -> 	"North Korea",
    "KR" -> 	"South Korea",
    "KW" -> 	"Kuwait",
    "KG" -> 	"Kyrgyzstan",
    "LA" -> 	"Laos",
    "LV" -> 	"Latvia",
    "LB" -> 	"Lebanon",
    "LS" -> 	"Lesotho",
    "LR" -> 	"Liberia",
    "LY" -> 	"Libya",
    "LI" -> 	"Liechtenstein",
    "LT" -> 	"Lithuania",
    "LU" -> 	"Luxembourg",
    "MO" -> 	"Macao",
    "MG" -> 	"Madagascar",
    "MW" -> 	"Malawi",
    "MY" -> 	"Malaysia",
    "MV" -> 	"Maldives",
    "ML" -> 	"Mali",
    "MT" -> 	"Malta",
    "MH" -> 	"Marshall Islands",
    "MQ" -> 	"Martinique",
    "MR" -> 	"Mauritania",
    "MU" -> 	"Mauritius",
    "YT" -> 	"Mayotte",
    "MX" -> 	"Mexico",
    "FM" -> 	"Micronesia",
    "MD" -> 	"Moldova",
    "MC" -> 	"Monaco",
    "MN" -> 	"Mongolia",
    "ME" -> 	"Montenegro",
    "MS" -> 	"Montserrat",
    "MA" -> 	"Morocco",
    "MZ" -> 	"Mozambique",
    "MM" -> 	"Myanmar",
    "NA" -> 	"Namibia",
    "NR" -> 	"Nauru",
    "NP" -> 	"Nepal",
    "NL" -> 	"Netherlands",
    "NC" -> 	"New Caledonia",
    "NZ" -> 	"New Zealand",
    "NI" -> 	"Nicaragua",
    "NE" -> 	"Niger",
    "NG" -> 	"Nigeria",
    "NU" -> 	"Niue",
    "NF" -> 	"Norfolk Island",
    "MP" -> 	"Northern Mariana Islands",
    "NO" -> 	"Norway",
    "OM" -> 	"Oman",
    "PK" -> 	"Pakistan",
    "PW" -> 	"Palau",
    "PS" -> 	"Palestine",
    "PA" -> 	"Panama",
    "PG" -> 	"Papua New Guinea",
    "PY" -> 	"Paraguay",
    "PE" -> 	"Peru",
    "PH" -> 	"Philippines",
    "PN" -> 	"Pitcairn",
    "PL" -> 	"Poland",
    "PT" -> 	"Portugal",
    "PR" -> 	"Puerto Rico",
    "QA" -> 	"Qatar",
    "MK" -> 	"Macedonia",
    "RO" -> 	"Romania",
    "RU" -> 	"Russia",
    "RW" -> 	"Rwanda",
    "RE" -> 	"Reunion",
    "BL" -> 	"Saint Barthelemy",
    "SH" -> 	"Saint Helena",
    "KN" -> 	"Saint Kitts and Nevis",
    "LC" -> 	"Saint Lucia",
    "MF" -> 	"Saint Martin (French part)",
    "PM" -> 	"Saint Pierre and Miquelon",
    "VC" -> 	"Saint Vincent and the Grenadines",
    "WS" -> 	"Samoa",
    "SM" -> 	"San Marino",
    "ST" -> 	"Sao Tome and Principe",
    "SA" -> 	"Saudi Arabia",
    "SN" -> 	"Senegal",
    "RS" -> 	"Serbia",
    "SC" -> 	"Seychelles",
    "SL" -> 	"Sierra Leone",
    "SG" -> 	"Singapore",
    "SX" -> 	"Sint Maarten (Dutch part)",
    "SK" -> 	"Slovakia",
    "SI" -> 	"Slovenia",
    "SB" -> 	"Solomon Islands",
    "SO" -> 	"Somalia",
    "ZA" -> 	"South Africa",
    "GS" -> 	"South Georgia and the South Sandwich Islands",
    "SS" -> 	"South Sudan",
    "ES" -> 	"Spain",
    "LK" -> 	"Sri Lanka",
    "SD" -> 	"Sudan",
    "SR" -> 	"Suriname",
    "SJ" -> 	"Svalbard and Jan Mayen",
    "SE" -> 	"Sweden",
    "CH" -> 	"Switzerland",
    "SY" -> 	"Syria",
    "TW" -> 	"Taiwan",
    "TJ" -> 	"Tajikistan",
    "TZ" -> 	"Tanzania",
    "TH" -> 	"Thailand",
    "TL" -> 	"Timor-Leste",
    "TG" -> 	"Togo",
    "TK" -> 	"Tokelau",
    "TO" -> 	"Tonga",
    "TT" -> 	"Trinidad and Tobago",
    "TN" -> 	"Tunisia",
    "TR" -> 	"Turkey",
    "TM" -> 	"Turkmenistan",
    "TC" -> 	"Turks and Caicos Islands",
    "TV" -> 	"Tuvalu",
    "UG" -> 	"Uganda",
    "UA" -> 	"Ukraine",
    "AE" -> 	"United Arab Emirates",
    "GB" -> 	"United Kingdom",
    "UM" -> 	"United States Minor Outlying Islands (the)",
    "US" -> 	"United States",
    "UY" -> 	"Uruguay",
    "UZ" -> 	"Uzbekistan",
    "VU" -> 	"Vanuatu",
    "VE" -> 	"Venezuela",
    "VN" -> 	"Vietnam",
    "VG" -> 	"Virgin Islands (British)",
    "VI" -> 	"Virgin Islands",
    "WF" -> 	"Wallis and Futuna",
    "EH" -> 	"Western Sahara",
    "YE" -> 	"Yemen",
    "ZM" -> 	"Zambia",
    "ZW" -> 	"Zimbabwe",
    "AX" -> 	"Aland Islands"
  )

  val country_codes_a3: Map[String, String] = Map(
    "AFG" ->	"Afghanistan",
    "ALB" ->	"Albania",
    "DZA" ->	"Algeria",
    "ASM" ->	"American Samoa",
    "AND" ->	"Andorra",
    "AGO" ->	"Angola",
    "AIA" ->	"Anguilla",
    "ATA" ->	"Antarctica",
    "ATG" ->	"Antigua and Barbuda",
    "ARG" ->	"Argentina",
    "ARM" ->	"Armenia",
    "ABW" ->	"Aruba",
    "AUS" ->	"Australia",
    "AUT" ->	"Austria",
    "AZE" ->	"Azerbaijan",
    "BHS" ->	"Bahamas",
    "BHR" ->	"Bahrain",
    "BGD" ->	"Bangladesh",
    "BRB" ->	"Barbados",
    "BLR" ->	"Belarus",
    "BEL" ->	"Belgium",
    "BLZ" ->	"Belize",
    "BEN" ->	"Benin",
    "BMU" ->	"Bermuda",
    "BTN" ->	"Bhutan",
    "BOL" ->	"Bolivia",
    "BES" ->	"Bonaire, Sint Eustatius and Saba",
    "BIH" ->	"Bosnia and Herzegovina",
    "BWA" ->	"Botswana",
    "BVT" ->	"Bouvet Island",
    "BRA" ->	"Brazil",
    "IOT" ->	"British Indian Ocean Territory",
    "BRN" ->	"Brunei Darussalam",
    "BGR" ->	"Bulgaria",
    "BFA" ->	"Burkina Faso",
    "BDI" ->	"Burundi",
    "CPV" ->	"Cabo Verde",
    "KHM" ->	"Cambodia",
    "CMR" ->	"Cameroon",
    "CAN" ->	"Canada",
    "CYM" ->	"Cayman Islands",
    "CAF" ->	"Central African Republic",
    "TCD" ->	"Chad",
    "CHL" ->	"Chile",
    "CHN" ->	"China",
    "CXR" ->	"Christmas Island",
    "CCK" ->	"Cocos (Keeling) Islands",
    "COL" ->	"Colombia",
    "COM" ->	"Comoros",
    "COD" ->	"Democratic Republic of the Congo",
    "COG" ->	"Congo",
    "COK" ->	"Cook Islands",
    "CRI" ->	"Costa Rica",
    "HRV" ->	"Croatia",
    "CUB" ->	"Cuba",
    "CUW" ->	"Curacao",
    "CYP" ->	"Cyprus",
    "CZE" ->	"Czechia",
    "CIV" ->	"Cote d'Ivoire",
    "DNK" ->	"Denmark",
    "DJI" ->	"Djibouti",
    "DMA" ->	"Dominica",
    "DOM" ->	"Dominican Republic",
    "ECU" ->	"Ecuador",
    "EGY" ->	"Egypt",
    "SLV" ->	"El Salvador",
    "GNQ" ->	"Equatorial Guinea",
    "ERI" ->	"Eritrea",
    "EST" ->	"Estonia",
    "SWZ" ->	"Eswatini",
    "ETH" ->	"Ethiopia",
    "FLK" ->	"Falkland Islands",
    "FRO" ->	"Faroe Islands",
    "FJI" ->	"Fiji",
    "FIN" ->	"Finland",
    "FRA" ->	"France",
    "GUF" ->	"French Guiana",
    "PYF" ->	"French Polynesia",
    "ATF" ->	"French Southern Territories",
    "GAB" ->	"Gabon",
    "GMB" ->	"Gambia",
    "GEO" ->	"Georgia",
    "DEU" ->	"Germany",
    "GHA" ->	"Ghana",
    "GIB" ->	"Gibraltar",
    "GRC" ->	"Greece",
    "GRL" ->	"Greenland",
    "GRD" ->	"Grenada",
    "GLP" ->	"Guadeloupe",
    "GUM" ->	"Guam",
    "GTM" ->	"Guatemala",
    "GGY" ->	"Guernsey",
    "GIN" ->	"Guinea",
    "GNB" ->	"Guinea-Bissau",
    "GUY" ->	"Guyana",
    "HTI" ->	"Haiti",
    "HMD" ->	"Heard Island and McDonald Islands",
    "VAT" ->	"Holy See",
    "HND" ->	"Honduras",
    "HKG" ->	"Hong Kong",
    "HUN" ->	"Hungary",
    "ISL" ->	"Iceland",
    "IND" ->	"India",
    "IDN" ->	"Indonesia",
    "IRN" ->	"Iran",
    "IRQ" ->	"Iraq",
    "IRL" ->	"Ireland",
    "IMN" ->	"Isle of Man",
    "ISR" ->	"Israel",
    "ITA" ->	"Italy",
    "JAM" ->	"Jamaica",
    "JPN" ->	"Japan",
    "JEY" ->	"Jersey",
    "JOR" ->	"Jordan",
    "KAZ" ->	"Kazakhstan",
    "KEN" ->	"Kenya",
    "KIR" ->	"Kiribati",
    "PRK" ->	"North Korea",
    "KOR" ->	"South Korea",
    "KWT" ->	"Kuwait",
    "KGZ" ->	"Kyrgyzstan",
    "LAO" ->	"Laos",
    "LVA" ->	"Latvia",
    "LBN" ->	"Lebanon",
    "LSO" ->	"Lesotho",
    "LBR" ->	"Liberia",
    "LBY" ->	"Libya",
    "LIE" ->	"Liechtenstein",
    "LTU" ->	"Lithuania",
    "LUX" ->	"Luxembourg",
    "MAC" ->	"Macao",
    "MDG" ->	"Madagascar",
    "MWI" ->	"Malawi",
    "MYS" ->	"Malaysia",
    "MDV" ->	"Maldives",
    "MLI" ->	"Mali",
    "MLT" ->	"Malta",
    "MHL" ->	"Marshall Islands",
    "MTQ" ->	"Martinique",
    "MRT" ->	"Mauritania",
    "MUS" ->	"Mauritius",
    "MYT" ->	"Mayotte",
    "MEX" ->	"Mexico",
    "FSM" ->	"Micronesia",
    "MDA" ->	"Moldova",
    "MCO" ->	"Monaco",
    "MNG" ->	"Mongolia",
    "MNE" ->	"Montenegro",
    "MSR" ->	"Montserrat",
    "MAR" ->	"Morocco",
    "MOZ" ->	"Mozambique",
    "MMR" ->	"Myanmar",
    "NAM" ->	"Namibia",
    "NRU" ->	"Nauru",
    "NPL" ->	"Nepal",
    "NLD" ->	"Netherlands",
    "NCL" ->	"New Caledonia",
    "NZL" ->	"New Zealand",
    "NIC" ->	"Nicaragua",
    "NER" ->	"Niger",
    "NGA" ->	"Nigeria",
    "NIU" ->	"Niue",
    "NFK" ->	"Norfolk Island",
    "MNP" ->	"Northern Mariana Islands",
    "NOR" ->	"Norway",
    "OMN" ->	"Oman",
    "PAK" ->	"Pakistan",
    "PLW" ->	"Palau",
    "PSE" ->	"Palestine",
    "PAN" ->	"Panama",
    "PNG" ->	"Papua New Guinea",
    "PRY" ->	"Paraguay",
    "PER" ->	"Peru",
    "PHL" ->	"Philippines",
    "PCN" ->	"Pitcairn",
    "POL" ->	"Poland",
    "PRT" ->	"Portugal",
    "PRI" ->	"Puerto Rico",
    "QAT" ->	"Qatar",
    "MKD" ->	"Macedonia",
    "ROU" ->	"Romania",
    "RUS" ->	"Russia",
    "RWA" ->	"Rwanda",
    "REU" ->	"Reunion",
    "BLM" ->	"Saint Barthelemy",
    "SHN" ->	"Saint Helena",
    "KNA" ->	"Saint Kitts and Nevis",
    "LCA" ->	"Saint Lucia",
    "MAF" ->	"Saint Martin (French part)",
    "SPM" ->	"Saint Pierre and Miquelon",
    "VCT" ->	"Saint Vincent and the Grenadines",
    "WSM" ->	"Samoa",
    "SMR" ->	"San Marino",
    "STP" ->	"Sao Tome and Principe",
    "SAU" ->	"Saudi Arabia",
    "SEN" ->	"Senegal",
    "SRB" ->	"Serbia",
    "SYC" ->	"Seychelles",
    "SLE" ->	"Sierra Leone",
    "SGP" ->	"Singapore",
    "SXM" ->	"Sint Maarten (Dutch part)",
    "SVK" ->	"Slovakia",
    "SVN" ->	"Slovenia",
    "SLB" ->	"Solomon Islands",
    "SOM" ->	"Somalia",
    "ZAF" ->	"South Africa",
    "SGS" ->	"South Georgia and the South Sandwich Islands",
    "SSD" ->	"South Sudan",
    "ESP" ->	"Spain",
    "LKA" ->	"Sri Lanka",
    "SDN" ->	"Sudan",
    "SUR" ->	"Suriname",
    "SJM" ->	"Svalbard and Jan Mayen",
    "SWE" ->	"Sweden",
    "CHE" ->	"Switzerland",
    "SYR" ->	"Syria",
    "TWN" ->	"Taiwan",
    "TJK" ->	"Tajikistan",
    "TZA" ->	"Tanzania",
    "THA" ->	"Thailand",
    "TLS" ->	"Timor-Leste",
    "TGO" ->	"Togo",
    "TKL" ->	"Tokelau",
    "TON" ->	"Tonga",
    "TTO" ->	"Trinidad and Tobago",
    "TUN" ->	"Tunisia",
    "TUR" ->	"Turkey",
    "TKM" ->	"Turkmenistan",
    "TCA" ->	"Turks and Caicos Islands",
    "TUV" ->	"Tuvalu",
    "UGA" ->	"Uganda",
    "UKR" ->	"Ukraine",
    "ARE" ->	"United Arab Emirates",
    "GBR" ->	"United Kingdom",
    "UMI" ->	"United States Minor Outlying Islands (the)",
    "USA" ->	"United States",
    "URY" ->	"Uruguay",
    "UZB" ->	"Uzbekistan",
    "VUT" ->	"Vanuatu",
    "VEN" ->	"Venezuela",
    "VNM" ->	"Vietnam",
    "VGB" ->	"Virgin Islands (British)",
    "VIR" ->	"Virgin Islands",
    "WLF" ->	"Wallis and Futuna",
    "ESH" ->	"Western Sahara",
    "YEM" ->	"Yemen",
    "ZMB" ->	"Zambia",
    "ZWE" ->	"Zimbabwe",
    "ALA" ->	"Aland Islands"
  )

  val country_codes_num: Map[Int, String] = Map(
    4	 -> "Afghanistan",
    8	 -> "Albania",
    12	 -> "Algeria",
    16	 -> "American Samoa",
    20	 -> "Andorra",
    24	 -> "Angola",
    660  -> "Anguilla",
    10	 -> "Antarctica",
    28	 -> "Antigua and Barbuda",
    32	 -> "Argentina",
    51	 -> "Armenia",
    533  -> "Aruba",
    36	 -> "Australia",
    40	 -> "Austria",
    31	 -> "Azerbaijan",
    44	 -> "Bahamas",
    48	 -> "Bahrain",
    50	 -> "Bangladesh",
    52	 -> "Barbados",
    112  -> "Belarus",
    56	 -> "Belgium",
    84	 -> "Belize",
    204  -> "Benin",
    60	 -> "Bermuda",
    64	 -> "Bhutan",
    68	 -> "Bolivia",
    535  -> "Bonaire, Sint Eustatius and Saba",
    70	 -> "Bosnia and Herzegovina",
    72	 -> "Botswana",
    74	 -> "Bouvet Island",
    76	 -> "Brazil",
    86	 -> "British Indian Ocean Territory",
    96	 -> "Brunei Darussalam",
    100  -> "Bulgaria",
    854  -> "Burkina Faso",
    108  -> "Burundi",
    132  -> "Cabo Verde",
    116  -> "Cambodia",
    120  -> "Cameroon",
    124  -> "Canada",
    136  -> "Cayman Islands",
    140  -> "Central African Republic",
    148  -> "Chad",
    152  -> "Chile",
    156  -> "China",
    162  -> "Christmas Island",
    166  -> "Cocos (Keeling) Islands",
    170  -> "Colombia",
    174  -> "Comoros",
    180  -> "Democratic Republic of the Congo",
    178  -> "Congo",
    184  -> "Cook Islands",
    188  -> "Costa Rica",
    191  -> "Croatia",
    192  -> "Cuba",
    531  -> "Curacao",
    196  -> "Cyprus",
    203  -> "Czechia",
    384  -> "Cote d'Ivoire",
    208  -> "Denmark",
    262  -> "Djibouti",
    212  -> "Dominica",
    214  -> "Dominican Republic",
    218  -> "Ecuador",
    818  -> "Egypt",
    222  -> "El Salvador",
    226  -> "Equatorial Guinea",
    232  -> "Eritrea",
    233  -> "Estonia",
    748  -> "Eswatini",
    231  -> "Ethiopia",
    238  -> "Falkland Islands",
    234  -> "Faroe Islands",
    242  -> "Fiji",
    246  -> "Finland",
    250  -> "France",
    254  -> "French Guiana",
    258  -> "French Polynesia",
    260  -> "French Southern Territories",
    266  -> "Gabon",
    270  -> "Gambia",
    268  -> "Georgia",
    276  -> "Germany",
    288  -> "Ghana",
    292  -> "Gibraltar",
    300  -> "Greece",
    304  -> "Greenland",
    308  -> "Grenada",
    312  -> "Guadeloupe",
    316  -> "Guam",
    320  -> "Guatemala",
    831  -> "Guernsey",
    324  -> "Guinea",
    624  -> "Guinea-Bissau",
    328  -> "Guyana",
    332  -> "Haiti",
    334  -> "Heard Island and McDonald Islands",
    336  -> "Holy See",
    340  -> "Honduras",
    344  -> "Hong Kong",
    348  -> "Hungary",
    352  -> "Iceland",
    356  -> "India",
    360  -> "Indonesia",
    364  -> "Iran",
    368  -> "Iraq",
    372  -> "Ireland",
    833  -> "Isle of Man",
    376  -> "Israel",
    380  -> "Italy",
    388  -> "Jamaica",
    392  -> "Japan",
    832  -> "Jersey",
    400  -> "Jordan",
    398  -> "Kazakhstan",
    404  -> "Kenya",
    296  -> "Kiribati",
    408  -> "North Korea",
    410  -> "South Korea",
    414  -> "Kuwait",
    417  -> "Kyrgyzstan",
    418  -> "Laos",
    428  -> "Latvia",
    422  -> "Lebanon",
    426  -> "Lesotho",
    430  -> "Liberia",
    434  -> "Libya",
    438  -> "Liechtenstein",
    440  -> "Lithuania",
    442  -> "Luxembourg",
    446  -> "Macao",
    450  -> "Madagascar",
    454  -> "Malawi",
    458  -> "Malaysia",
    462  -> "Maldives",
    466  -> "Mali",
    470  -> "Malta",
    584  -> "Marshall Islands",
    474  -> "Martinique",
    478  -> "Mauritania",
    480  -> "Mauritius",
    175  -> "Mayotte",
    484  -> "Mexico",
    583  -> "Micronesia",
    498  -> "Moldova",
    492  -> "Monaco",
    496  -> "Mongolia",
    499  -> "Montenegro",
    500  -> "Montserrat",
    504  -> "Morocco",
    508  -> "Mozambique",
    104  -> "Myanmar",
    516  -> "Namibia",
    520  -> "Nauru",
    524  -> "Nepal",
    528  -> "Netherlands",
    540  -> "New Caledonia",
    554  -> "New Zealand",
    558  -> "Nicaragua",
    562  -> "Niger",
    566  -> "Nigeria",
    570  -> "Niue",
    574  -> "Norfolk Island",
    580  -> "Northern Mariana Islands",
    578  -> "Norway",
    512  -> "Oman",
    586  -> "Pakistan",
    585  -> "Palau",
    275  -> "Palestine",
    591  -> "Panama",
    598  -> "Papua New Guinea",
    600  -> "Paraguay",
    604  -> "Peru",
    608  -> "Philippines",
    612  -> "Pitcairn",
    616  -> "Poland",
    620  -> "Portugal",
    630  -> "Puerto Rico",
    634  -> "Qatar",
    807  -> "Macedonia",
    642  -> "Romania",
    643  -> "Russia",
    646  -> "Rwanda",
    638  -> "Reunion",
    652  -> "Saint Barthelemy",
    654  -> "Saint Helena",
    659  -> "Saint Kitts and Nevis",
    662  -> "Saint Lucia",
    663  -> "Saint Martin (French part)",
    666  -> "Saint Pierre and Miquelon",
    670  -> "Saint Vincent and the Grenadines",
    882  -> "Samoa",
    674  -> "San Marino",
    678  -> "Sao Tome and Principe",
    682  -> "Saudi Arabia",
    686  -> "Senegal",
    688  -> "Serbia",
    690  -> "Seychelles",
    694  -> "Sierra Leone",
    702  -> "Singapore",
    534  -> "Sint Maarten (Dutch part)",
    703  -> "Slovakia",
    705  -> "Slovenia",
    90	 -> "Solomon Islands",
    706  -> "Somalia",
    710  -> "South Africa",
    239  -> "South Georgia and the South Sandwich Islands",
    728  -> "South Sudan",
    724  -> "Spain",
    144  -> "Sri Lanka",
    729  -> "Sudan",
    740  -> "Suriname",
    744  -> "Svalbard and Jan Mayen",
    752  -> "Sweden",
    756  -> "Switzerland",
    760  -> "Syria",
    158  -> "Taiwan",
    762  -> "Tajikistan",
    834  -> "Tanzania",
    764  -> "Thailand",
    626  -> "Timor-Leste",
    768  -> "Togo",
    772  -> "Tokelau",
    776  -> "Tonga",
    780  -> "Trinidad and Tobago",
    788  -> "Tunisia",
    792  -> "Turkey",
    795  -> "Turkmenistan",
    796  -> "Turks and Caicos Islands",
    798  -> "Tuvalu",
    800  -> "Uganda",
    804  -> "Ukraine",
    784  -> "United Arab Emirates",
    826  -> "United Kingdom",
    581  -> "United States Minor Outlying Islands (the)",
    840  -> "United States",
    858  -> "Uruguay",
    860  -> "Uzbekistan",
    548  -> "Vanuatu",
    862  -> "Venezuela",
    704  -> "Vietnam",
    92	 -> "Virgin Islands (British)",
    850  -> "Virgin Islands",
    876  -> "Wallis and Futuna",
    732  -> "Western Sahara",
    887  -> "Yemen",
    894  -> "Zambia",
    716  -> "Zimbabwe",
    248  -> "Aland Islands"
  )

  val regions_dictionary: Map[String, List[String]] = Map(
    "Africa" ->
      List(
        "Algeria",
        "Angola",
        "Benin",
        "Botswana",
        "Burkina Faso",
        "Burundi",
        "Cameroon",
        "Cape Verde",
        "Central African Republic",
        "Chad",
        "Comoros",
        "Cote d'Ivoire",
        "Democratic Republic of the Congo",
        "Djibouti",
        "Egypt",
        "Equatorial Guinea",
        "Eritrea",
        "Ethiopia",
        "Gabon",
        "Gambia",
        "Ghana",
        "Guinea",
        "Guinea-Bissau",
        "Kenya",
        "Lesotho",
        "Liberia",
        "Libya",
        "Madagascar",
        "Malawi",
        "Mali",
        "Mauritania",
        "Mauritius",
        "Morocco",
        "Mozambique",
        "Namibia",
        "Niger",
        "Nigeria",
        "Republic of the Congo",
        "Reunion",
        "Rwanda",
        "Saint Helena",
        "Sao Tome and Principe",
        "Senegal",
        "Seychelles",
        "Sierra Leone",
        "Somalia",
        "South Africa",
        "South Sudan",
        "Sudan",
        "Swaziland",
        "Tanzania",
        "Togo",
        "Tunisia",
        "Uganda",
        "Western Sahara",
        "Zambia",
        "Zimbabwe"
      ),
    "Asia" ->
      List(
        "Afghanistan",
        "Armenia",
        "Azerbaijan",
        "Bahrain",
        "Bangladesh",
        "Bhutan",
        "Brunei",
        "Burma",
        "Cambodia",
        "China",
        "Cyprus",
        "East Timor",
        "Georgia",
        "Hong Kong",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Israel",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Lebanon",
        "Macau",
        "Malaysia",
        "Maldives",
        "Mongolia",
        "Nepal",
        "North Korea",
        "Oman",
        "Pakistan",
        "Philippines",
        "Qatar",
        "Saudi Arabia",
        "Singapore",
        "South Korea",
        "Sri Lanka",
        "Syria",
        "Taiwan",
        "Tajikistan",
        "Thailand",
        "Turkey",
        "Turkmenistan",
        "United Arab Emirates",
        "Uzbekistan",
        "Vietnam",
        "Yemen"
      ),
    "Caribbean" ->
      List(
        "Anguilla",
        "Antigua and Barbuda",
        "Aruba",
        "The Bahamas",
        "Barbados",
        "Bermuda",
        "British Virgin Islands",
        "Cayman Islands",
        "Cuba",
        "Dominica",
        "Dominican Republic",
        "Grenada",
        "Guadeloupe",
        "Haiti",
        "Jamaica",
        "Martinique",
        "Montserrat",
        "Netherlands Antilles",
        "Puerto Rico",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Vincent and the Grenadines",
        "Trinidad and Tobago",
        "Turks and Caicos Islands",
        "U.S. Virgin Islands"
      ),
    "Central America" ->
      List(
        "Belize",
        "Costa Rica",
        "El Salvador",
        "Guatemala",
        "Honduras",
        "Nicaragua",
        "Panama"
      ),
    "Europe" ->
      List(
        "Albania",
        "Andorra",
        "Austria",
        "Belarus",
        "Belgium",
        "Bosnia and Herzegovina",
        "Bulgaria",
        "Croatia",
        "Czech Republic",
        "Denmark",
        "Estonia",
        "Finland",
        "France",
        "Germany",
        "Gibraltar",
        "Greece",
        "Holy See",
        "Hungary",
        "Iceland",
        "Ireland",
        "Italy",
        "Kosovo",
        "Latvia",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macedonia",
        "Malta",
        "Moldova",
        "Monaco",
        "Montenegro",
        "Netherlands",
        "Norway",
        "Poland",
        "Portugal",
        "Romania",
        "Russia",
        "San Marino",
        "Slovak Republic",
        "Slovenia",
        "Spain",
        "Serbia",
        "Serbia and Montenegro",
        "Sweden",
        "Switzerland",
        "Ukraine",
        "United Kingdom"
      ),
    "North America" ->
      List(
        "Canada",
        "Greenland",
        "Mexico",
        "Saint Pierre and Miquelon",
        "United States"
      ),
    "Oceania" ->
      List(
        "American Samoa",
        "Australia",
        "Christmas Island",
        "Cocos (Keeling) Islands",
        "Cook Islands",
        "Federated States of Micronesia",
        "Fiji",
        "French Polynesia",
        "Guam",
        "Kiribati",
        "Marshall Islands",
        "Nauru",
        "New Caledonia",
        "New Zealand",
        "Niue",
        "Northern Mariana Islands",
        "Palau",
        "Papua New Guinea",
        "Pitcairn Islands",
        "Samoa",
        "Solomon Islands",
        "Tokelau",
        "Tonga",
        "Tuvalu",
        "Vanuatu",
        "Wallis and Futuna Islands"
      ),
    "South America" ->
      List(
        "Argentina",
        "Bolivia",
        "Brazil",
        "Chile",
        "Colombia",
        "Ecuador",
        "Falkland Islands",
        "French Guiana",
        "Guyana",
        "Paraguay",
        "Peru",
        "Suriname",
        "Uruguay",
        "Venezuela"
      )
  )

  val development_ranking: Map[String, List[String]] = Map(
    "First" -> List(
      "Norway",
      "Switzerland",
      "Ireland",
      "Germany",
      "Hong Kong",
      "Australia",
      "Iceland",
      "Sweden",
      "Singapore",
      "Netherlands",
      "Denmark",
      "Finland",
      "Canada",
      "New Zealand",
      "United Kingdom",
      "United States",
      "Belgium",
      "Liechtenstein",
      "Japan",
      "Austria",
      "Luxembourg",
      "Israel",
      "South Korea",
      "Slovenia",
      "Spain",
      "Czechia",
      "France",
      "Malta",
      "Italy",
      "Estonia",
      "Cyprus",
      "Greece",
      "Poland",
      "Lithuania",
      "United Arab Emirates",
      "Andorra",
      "Saudi Arabia",
      "Slovakia",
      "Latvia",
      "Portugal",
      "Qatar",
      "Chile",
      "Brunei Darussalam",
      "Hungary",
      "Bahrain",
      "Croatia",
      "Oman",
      "Argentina",
      "Russian Federation",
      "Belarus",
      "Kazakhstan",
      "Bulgaria",
      "Montenegro",
      "Romania",
      "Palau",
      "Barbados",
      "Kuwait",
      "Uruguay",
      "Turkey",
      "Bahamas",
      "Malaysia",
      "Seychelles",
      "Serbia"
    ),
    "Second" -> List(
      "Trinidad and Tobago",
      "Iran",
      "Mauritius",
      "Panama",
      "Costa Rica",
      "Albania",
      "Georgia",
      "Sri Lanka",
      "Cuba",
      "Saint Kitts and Nevis",
      "Antigua and Barbuda",
      "Bosnia and Herzegovina",
      "Mexico",
      "Thailand",
      "Grenada",
      "Brazil",
      "Colombia",
      "Armenia",
      "Algeria",
      "North Macedonia",
      "Peru",
      "China",
      "Ecuador",
      "Azerbaijan",
      "Ukraine",
      "Dominican Republic",
      "Saint Lucia",
      "Tunisia",
      "Mongolia",
      "Lebanon",
      "Botswana",
      "Saint Vincent and the Grenadines",
      "Jamaica",
      "Venezuela",
      "Dominica",
      "Fiji",
      "Paraguay",
      "Suriname",
      "Jordan",
      "Belize",
      "Maldives",
      "Tonga",
      "Philippines",
      "Moldova",
      "Turkmenistan",
      "Uzbekistan",
      "Libya",
      "Indonesia",
      "Samoa",
      "South Africa",
      "Bolivia",
      "Gabon",
      "Egypt",
      "Marshall Islands",
      "Viet Nam",
      "Palestine",
      "Iraq",
      "Morocco",
      "Kyrgyzstan",
      "Guyana",
      "El Salvador",
      "Tajikistan",
      "Cabo Verde",
      "Guatemala",
    ),
    "Third" -> List(
      "Nicaragua",
      "India",
      "Namibia",
      "Timor-Leste",
      "Honduras",
      "Kiribati",
      "Bhutan",
      "Bangladesh",
      "Micronesia",
      "Sao Tome and Principe",
      "Congo",
      "Eswatini",
      "Laos",
      "Vanuatu",
      "Ghana",
      "Zambia",
      "Equatorial Guinea",
      "Myanmar",
      "Cambodia",
      "Kenya",
      "Nepal",
      "Angola",
      "Cameroon",
      "Zimbabwe",
      "Pakistan",
      "Solomon Islands",
      "Syrian Arab Republic",
      "Papua New Guinea",
      "Comoros",
      "Rwanda",
      "Nigeria",
      "Tanzania",
      "Uganda",
      "Mauritania",
      "Madagascar",
      "Benin",
      "Lesotho",
      "Cote d'Ivoire",
      "Senegal",
      "Togo",
      "Sudan",
      "Haiti",
      "Afghanistan",
      "Djibouti",
      "Malawi",
      "Ethiopia",
      "Gambia",
      "Guinea",
      "Liberia",
      "Yemen",
      "Guinea-Bissau",
      "Democratic Republic of the Congo",
      "Mozambique",
      "Sierra Leone",
      "Burkina Faso",
      "Eritrea",
      "Mali",
      "Burundi",
      "South Sudan",
      "Chad",
      "Central African Republic",
      "Niger"
    )
  )

  def countryCodeLookup(str: String): String = {
    if (str.length == 2)
      country_codes_a2(str)
    else if (str.length == 3)
      country_codes_a3(str)
    else
      "Error"
  }

  def countryCodeLookup(n: Int): String = {
    country_codes_num(n)
  }

  def borderingCountries(str: String): List[String] = {
    borders_dictionary(str)
  }

  def isLandLocked(str: String): Boolean = {
    landlocked.contains(str)
  }

  def isDoublyLandLocked(str: String): Boolean = {
    doubly_landlocked.contains(str)
  }

  def regionCountries(str: String): List[String] ={
    regions_dictionary(str)
  }

}
